### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1082]
##### Tasks:
- Package Manager UI:
  - [x] #1344: Package Manager Xaml
  - [x] #1342: Package List Xaml
  - [x] #1341: Package Details Xaml
  - [x] #1343: Available Packages ViewModel 
  - [x] #1346: Installed Packages ViewModel 
  - [x] #1347: Loaded Packages ViewModel 
  - [ ] #1345: Specify global list of package repos
  - [x] #1348: Add Search Textbox
  - [x] #1406: Wire up Install/Uninstall buttons
  - [x] #1412: Always update Installed Packages and Loaded Packages lists

**Comment by MikhailArkhipov** [comment]
Closing since majority of items are complete. We can open another epic in 0.4 for #1488 and friends
